version: "3.3"
services:
  automod:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LEMMY_DOMAIN=<<yourlemmydomain.foo >>
      - LEMMY_USERNAME=<<Your Bot's Username (created within Lemmy)>>
      - LEMMY_PASSWORD=<<Your Bot's Password (created within Lemmy)>>
      - USE_SQLITE=1
      - THREATIVORE_ADMIN_URL=<<Full URL to your own admin profile, such as lemmy.foo/u/yourusername>>
    restart: always
    volumes:
      - /path/to/volume:./volumes
    ports:
      - 8000:8080

